libraries:
    - api_key: libiblc=eyJpdiI6IlJ0K2t5bkMxTGxpR1RnV2oiLCJ0YWciOiJyK0lMeWx4UWs1KzhXRFZmckVLR3lBPT0iLCJjaXBoZXJ0ZXh0IjoiT0VSd1NXVjNlVGhqVkdGUVFXaENSMEZwVTNkM1ZIUkZWelp4YVhsVWNITTJaRVp3ZG5KVlUyRkdaM2szT0RCVlVVaGxjVnB3T0V0NGRHaEJiRXBZTmtGS1RFeHBXbTFVZUdsVU9FNWpaRUZzY0dObmFFTkdLdz09In0%3D; PHPSESSID=709769653695b96ffca1e788a26d2a50
      other_collection_ids:
        - "1807272"
      type: libib
      wanted_collection_id: "1807273"
series:
    - name: One Piece
      id: one-piece
      isbn_blacklist:
        - one
        - two
        - three
      source: viz
      source_settings:
        maximum_backlog: 2
        delay_between: 100ms
      key: one-piece
    - name: Miss Kobayashi's Dragon Maid
      id: List_of_Miss_Kobayashi's_Dragon_Maid_chapters
      isbn_blacklist: []
      source: wikipedia
      source_settings:
        volume_header: No.
        title_header: null
        isbn_header: English ISBN
        tables:
            - 0
      key: dragon-maid
    - name: 'Miss Kobayashi''s Dragon Maid: Kanna''s Daily Life'
      id: List_of_Miss_Kobayashi's_Dragon_Maid_chapters
      isbn_blacklist: []
      source: wikipedia
      source_settings:
        volume_header: No.
        title_header: null
        isbn_header: English ISBN
        tables:
            - 1
      key: kanna
    - name: 'Miss Kobayashi''s Dragon Maid: Elma''s Office Lady Diary'
      id: List_of_Miss_Kobayashi's_Dragon_Maid_chapters
      isbn_blacklist: []
      source: wikipedia
      source_settings:
        volume_header: No.
        title_header: null
        isbn_header: English ISBN
        tables:
            - 2
      key: elma
    - name: 'Miss Kobayashi''s Dragon Maid: Fafnir the Recluse'
      id: List_of_Miss_Kobayashi's_Dragon_Maid_chapters
      isbn_blacklist: []
      source: wikipedia
      source_settings:
        volume_header: No.
        title_header: null
        isbn_header: English ISBN
        tables:
            - 4
      key: fafnir
    - name: 'Zom 100: Bucket List of the Dead'
      id: zom-100-bucket-list-of-the-dead
      isbn_blacklist: []
      source: viz
      source_settings:
        maximum_backlog: 2
        delay_between: 100ms
      key: zom-100
    - name: Chainsaw man
      id: chainsaw-man
      isbn_blacklist: []
      source: viz
      source_settings:
        maximum_backlog: 2
        delay_between: 100ms
      key: chainsaw-man
    - name: Accel World
      id: Accel_World
      isbn_blacklist: []
      source: wikipedia
      source_settings:
        volume_header: No.
        title_header: Title
        isbn_header: English release date
        tables:
            - 0
      key: accel-world
    - name: So I'm a Spider, So What?
      id: So_I'm_a_Spider,_So_What?
      isbn_blacklist: []
      source: wikipedia
      source_settings:
        volume_header: No.
        title_header: null
        isbn_header: English ISBN
        tables:
            - 0
      key: spider-so-what
    - name: Bocchi the Rock!
      id: Bocchi_the_Rock!
      isbn_blacklist: []
      source: wikipedia
      source_settings:
        volume_header: No.
        title_header: null
        isbn_header: English ISBN
        tables: []
      key: bocchi
    - name: Is It Wrong to Try to Pick Up Girls in a Dungeon?
      id: List_of_Is_It_Wrong_to_Try_to_Pick_Up_Girls_in_a_Dungeon?_light_novels
      isbn_blacklist: []
      source: wikipedia
      source_settings:
        volume_header: No.
        title_header: null
        isbn_header: English ISBN
        tables:
            - 0
      key: dan-machi
    - name: Is It Wrong to Try to Pick Up Girls in a Dungeon? - Familia Chronicle
      id: List_of_Is_It_Wrong_to_Try_to_Pick_Up_Girls_in_a_Dungeon?_light_novels
      isbn_blacklist: []
      source: wikipedia
      source_settings:
        volume_header: No.
        title_header: Title
        isbn_header: English release date
        tables:
            - 1
      key: dan-machi-familia
    - name: Is It Wrong to Try to Pick Up Girls in a Dungeon? - Sword_Oratoria
      id: Sword_Oratoria
      isbn_blacklist: []
      source: wikipedia
      source_settings:
        volume_header: No.
        title_header: null
        isbn_header: English ISBN
        tables:
            - 0
      key: sword-oratoria
    - name: Overlord
      id: Overlord_(novel_series)
      isbn_blacklist: []
      source: wikipedia
      source_settings:
        volume_header: No.
        title_header: Title
        isbn_header: English release date
        tables:
            - 0
      key: overlord
    - name: Kaiju No. 8
      id: kaiju-no-8
      isbn_blacklist: []
      source: viz
      source_settings:
        maximum_backlog: 2
        delay_between: 100ms
      key: kaiji-8
    - name: Spy x Famliy
      id: spy-x-family
      isbn_blacklist: []
      source: viz
      source_settings:
        maximum_backlog: null
        delay_between: 25ms
      key: spy-x-family
