// Code generated by mockery v2.35.4. DO NOT EDIT.

package types

import (
	viper "github.com/spf13/viper"
	mock "github.com/stretchr/testify/mock"
)

// IConfigMock is an autogenerated mock type for the IConfig type
type IConfigMock struct {
	mock.Mock
}

// AddConfigPath provides a mock function with given fields: in
func (_m *IConfigMock) AddConfigPath(in string) {
	_m.Called(in)
}

// AutomaticEnv provides a mock function with given fields:
func (_m *IConfigMock) AutomaticEnv() {
	_m.Called()
}

// ReadInConfig provides a mock function with given fields:
func (_m *IConfigMock) ReadInConfig() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Set provides a mock function with given fields: key, value
func (_m *IConfigMock) Set(key string, value interface{}) {
	_m.Called(key, value)
}

// SetConfigName provides a mock function with given fields: in
func (_m *IConfigMock) SetConfigName(in string) {
	_m.Called(in)
}

// SetConfigType provides a mock function with given fields: in
func (_m *IConfigMock) SetConfigType(in string) {
	_m.Called(in)
}

// Unmarshal provides a mock function with given fields: rawVal, opts
func (_m *IConfigMock) Unmarshal(rawVal interface{}, opts ...viper.DecoderConfigOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, rawVal)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, ...viper.DecoderConfigOption) error); ok {
		r0 = rf(rawVal, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteConfig provides a mock function with given fields:
func (_m *IConfigMock) WriteConfig() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIConfigMock creates a new instance of IConfigMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIConfigMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *IConfigMock {
	mock := &IConfigMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
