// Code generated by mockery v2.35.4. DO NOT EDIT.

package types

import mock "github.com/stretchr/testify/mock"

// ISourceSettingsMock is an autogenerated mock type for the ISourceSettings type
type ISourceSettingsMock struct {
	mock.Mock
}

// Print provides a mock function with given fields: cmd
func (_m *ISourceSettingsMock) Print(cmd ICommand) error {
	ret := _m.Called(cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(ICommand) error); ok {
		r0 = rf(cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewISourceSettingsMock creates a new instance of ISourceSettingsMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISourceSettingsMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISourceSettingsMock {
	mock := &ISourceSettingsMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
